### ISSUE TITLE
Cutoff path calculations once the target is reached

### ISSUE THREAD

**Issue by waldyrious** [mohd-akram/languages#5]
For example, in https://mohd-akram.github.io/languages/?source=Julia&target=JavaScript, the whole subgraph between JavaScript and Python is unwarranted. More generally, the paths shown by the filtering function should have loops pruned out.

**Comment by waldyrious** [comment]
An intermediate step towards this end (or at least related to it) could be to replace the "directly" checkbox with a dropdown that would allow specifying the max number of hops desired.

**Comment by trn1ty** [comment]
I might be a bit late to the party but I agree here. I noticed this when trying Rust->JavaScript.

**Comment by mohd-akram** [comment]
Fixed.

**Comment by waldyrious** [comment]
Nice! I can confirm the fix works as expected. For future reference, the relevant commit is dd5e6a6ad.
