### ISSUE TITLE
Add more JVM-to-JS transpilers

### ISSUE THREAD

**Issue by waldyrious** [mohd-akram/languages#8]
Currently only TeaVM is covered here, but [Wikipedia also lists](https://en.wikipedia.org/wiki/Java_virtual_machine#Compilation_to_JavaScript):

> ...the compiler contained in [Dragome Web SDK](http://www.dragome.com/), [Bck2Brwsr](http://wiki.apidesign.org/wiki/Bck2Brwsr) and [j2js-compiler](https://github.com/decatur/j2js-compiler).

**Comment by mohd-akram** [comment]
Added in mohd-akram/compilers@0aecc108307e2eb8ecdd57fe49e46bfb5f834de3.
